version: 2.1
orbs:
  python: circleci/python@1.5.0
  #codecov: codecov/codecov@1.0.2
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    # environment:
    #   PYTHONPATH=./App
    #working_directory: ~/App
    steps:
      - checkout
      - python/install-packages:
           pkg-manager: pip

      - run:
          name: Setup Virtual Env
          command: |
            virtualenv -p python3.8 env
            echo "source ./env/bin/activate" >> $BASH_ENV

      - run:
          name: Install Python dependencies
          command:
            python -m pip install --upgrade pip
            pip install  -r requirements.txt
            pip install pytest
            pip install pytest-cov
            pip install pytest-html
      #- python/install-deps
      #- python/tests
      - run:
          name: Run tests
          command: python -m pytest --junitxml=test-reports/junit.xml --html=test-reports/report.html --cov=App/tests --cov-report=html:test-reports --self-contained-html


      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: Brief19T

workflows:
  main:
    jobs:
      - build-and-test

